### ISSUE TITLE
Pr.1: Ej.4.1: la función laQueEsMayor tiene paréntesis innecesarios

### ISSUE THREAD

**Issue by AbrSantiago** [as-ez/EstrD2023s1#10]
Recordá que los paréntesis en Haskell se usan principalmente para separar argumentos.

Nota: Si bien no se especifica qué hacer en caso de que tengan la misma edad, podrías devolver cualquiera de las dos en ves de tirar error.

**Comment by as-ez** [comment]
Corregido

**Comment by AbrSantiago** [comment]
COrregido
